### ISSUE TITLE
Sporadic transfer errors on a properly functioning bus

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pyuavcan#14]
Exceptions like below occur randomly, typically when the bus load exceeds 10% (at 1 Mbps):

```
Traceback (most recent call last):
  File "./drwatson_zubax_gnss.py", line 144, in safe_spin
    n.spin(timeout)
  File "pyuavcan/uavcan/node.py", line 328, in spin
    execute_once()
  File "pyuavcan/uavcan/node.py", line 324, in execute_once
    self._recv_frame(frame)
  File "pyuavcan/uavcan/node.py", line 247, in _recv_frame
    transfer.from_frames(transfer_frames)
  File "pyuavcan/uavcan/transport.py", line 587, in from_frames
    raise TransferError("Start of transmission set unexpectedly on frame {0}".format(idx))
uavcan.transport.TransferError: Start of transmission set unexpectedly on frame 4
```

This probably indicates that the library is losing frames. Libuavcan-based applications that simultaneously use the same bus do not experience any issues.

**Comment by pavel-kirienko** [comment]
https://github.com/UAVCAN/pyuavcan/pull/15
